import { Player } from '@rieken/app/components/player.type';

let restNPeaces: Player = {
  name: 'Mxda Roger’s Theyborhood',
  imageUrl: '/mxda-rogers-theyborhood.jpeg',
  derbyNumber: 100,
  url: 'player-url',
  status: 'Training Manager, Trainer & Skater',
  pronouns: ['they', 'them'],
  socials: {
    facebook: 'https://www.facebook.com/',
  }
};

let tangles: Player = {
  name: 'Tangles',
  imageUrl: '/tangles.jpeg',
  derbyNumber: 139,
  url: 'player-url',
  status: 'Head Coach, Board Member, Governance, Trainer, & Skater (jack of all trades)',
  pronouns: ['she', 'her'],
};

let hotCrossBunny: Player = {
  name: 'Hot Cross Bunny',
  imageUrl: '/hot-cross-bunny.jpeg',
  derbyNumber: 616,
  url: 'player-url',
  status: 'Skater',
  pronouns: ['she', 'her'],
  socials: {
    facebook: 'https://www.facebook.com/',
    instagram: 'https://www.instagram.com/',
    twitter: 'https://twitter.com/',
    tiktok: 'https://www.tiktok.com/',
    youtube: 'https://www.youtube.com/',
    twitch: 'https://www.twitch.tv/',
  }
};

let thembalina: Player = {
  name: 'Thembalina',
  imageUrl: '/thembalina.jpeg',
  derbyNumber: 337,
  url: 'player-url',
  status: 'Training Manager, Trainer & Skater',
  pronouns: ['they', 'them'],
};

let kineLeeKillz: Player = {
  name: 'Kine Lee Killz',
  imageUrl: '/kine-lee-killz.jpeg',
  derbyNumber: 187,
  url: 'player-url',
  status: '2023 Captain, Trainer & Skater',
  pronouns: ['she', 'her'],
};

const Players: Player[] = [
  restNPeaces,
  tangles,
  hotCrossBunny,
  thembalina,
  kineLeeKillz,
  {
    name: 'Ma-Killveli',
    imageUrl: '/ma-killveli.jpeg',
    derbyNumber: 21,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Belligerent Bex',
    imageUrl: '/belligerent-bex.jpeg',
    derbyNumber: 20,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Kitty Twister',
    imageUrl: '/kitty-twister.jpeg',
    derbyNumber: 37,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Twinkle Toes',
    imageUrl: '/twinkle-toes.jpeg',
    derbyNumber: 343,
    url: 'player-url',
    status: 'Dual Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Tonka',
    imageUrl: '/tonka.jpeg',
    derbyNumber: 42,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Violent Femme',
    imageUrl: '/violent-femme.jpeg',
    derbyNumber: 414,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Beckah Hipchecka',
    imageUrl: '/beckah-hipchecka.jpeg',
    derbyNumber: 361,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Bonnie Knoxville',
    imageUrl: '/bonnie-knoxville.jpeg',
    derbyNumber: 816,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Gender Bender',
    imageUrl: '/gender-bender.jpeg',
    derbyNumber: 22,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['he', 'they'],
  },
  {
    name: 'Goldie Knocks',
    imageUrl: '/goldie-knocks.jpeg',
    derbyNumber: 667,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Tiff',
    imageUrl: '/tiff.jpeg',
    derbyNumber: 88,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Momma Mayhem',
    imageUrl: '/momma-mayhem.jpeg',
    derbyNumber: 353,
    url: 'player-url',
    status: 'Rec Trainer & Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Poison Ash',
    imageUrl: '/poison-ash.jpeg',
    derbyNumber: 4,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Lacy Underalls',
    imageUrl: '/lacy-underalls.jpeg',
    derbyNumber: 1108,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Five Star Fancy',
    imageUrl: '/five-star-fancy.jpeg',
    derbyNumber: 514,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Quiet Fire',
    imageUrl: '/quiet-fire.jpeg',
    derbyNumber: 24,
    url: 'player-url',
    status: 'Marketing Manager & Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Milly Rock',
    imageUrl: '/milly-rock.jpeg',
    derbyNumber: 2321,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Chief',
    imageUrl: '/chief.jpeg',
    derbyNumber: 700,
    url: 'player-url',
    status: 'Interleague Manager & Skater',
    pronouns: ['he', 'him'],
  },
  {
    name: 'Mississippi Blues',
    imageUrl: '/mississippi-blues.jpeg',
    derbyNumber: 228,
    url: 'player-url',
    status: 'Membership Manager & Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Galaxy Girl',
    imageUrl: '/galaxy-girl.jpeg',
    derbyNumber: 73,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Deanne T. Krist',
    imageUrl: '/deanne-t-krist.jpeg',
    derbyNumber: 10,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['they', 'them'],
  },
  {
    name: 'Skevie Nyx',
    imageUrl: '/skevie-nyx.jpeg',
    derbyNumber: 13,
    url: 'player-url',
    status: 'Events Manager & Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Goody Two Bruise',
    imageUrl: '/goody-two-bruise.jpeg',
    derbyNumber: 307,
    url: 'player-url',
    status: 'Trainer & Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Wreckit Reese',
    imageUrl: '/wreckit-reese.jpeg',
    derbyNumber: 1989,
    url: 'player-url',
    status: 'Rec Trainer & Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Skela-Laur',
    imageUrl: '/skela-laur.jpeg',
    derbyNumber: 206,
    url: 'player-url',
    status: 'Bench Staff',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Trannysauras-Rex',
    imageUrl: '/trannysauras-rex.jpeg',
    derbyNumber: 614,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Lucy Goosey',
    imageUrl: '/lucy-goosey.jpeg',
    derbyNumber: 74,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'The Jebberwhack',
    imageUrl: '/the-jebberwhack.jpeg',
    derbyNumber: 11,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Trips&Queso',
    imageUrl: '/trips-and-queso.jpeg',
    derbyNumber: 9,
    url: 'player-url',
    status: 'Skater & NSO',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Amara',
    imageUrl: '/amara.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Viva Vendetta',
    imageUrl: '/viva-vendetta.jpeg',
    derbyNumber: 86,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Shreddy Krueger',
    imageUrl: '/shreddy-krueger.jpeg',
    derbyNumber: 618,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Malone',
    imageUrl: '/malone.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['they', 'them'],
  },
  {
    name: 'Purple Reign',
    imageUrl: '/purple-reign.jpeg',
    derbyNumber: 27,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Royal Payne',
    imageUrl: '/royal-payne.jpeg',
    derbyNumber: 33,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Lavender Menace',
    imageUrl: '/laveneder-menace.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Kamber',
    imageUrl: '/kamber.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'Skater',
    pronouns: ['she', 'her'],
  },
  {
    name: 'PsychoSis',
    imageUrl: '/psychosis.jpeg',
    derbyNumber: 27,
    url: 'player-url',
    status: 'Finance Manager',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Rickn-Bloc-Her',
    imageUrl: '/rickn-bloc-her.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'NSO',
    pronouns: [],
  },
  {
    name: 'Beatrix sKiddo',
    imageUrl: '/beatrix-skiddo.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'Bench Staff, Trainer & #1 Alumnae!',
    pronouns: ['she', 'her'],
  },
  {
    name: 'James Bondage',
    imageUrl: '/james-bondage.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'Head Official',
    pronouns: ['he', 'him'],
  },
  {
    name: 'Pi Radical',
    imageUrl: '/pi-radical.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'Official',
    pronouns: ['he', 'him'],
  },
  {
    name: 'Quama Sutra',
    imageUrl: '/quama-sutra.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'Official',
    pronouns: ['he', 'him'],
  },
  {
    name: 'PR Mageddon',
    imageUrl: '/pr-mageddon.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'Announcer',
    pronouns: ['he', 'him'],
  },
  {
    name: 'The Countess',
    imageUrl: '/the-countess.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'NSO',
    pronouns: ['she', 'her'],
  },
  {
    name: 'Bourbon Decay',
    imageUrl: '/bourbon-decay.jpeg',
    derbyNumber: 0,
    url: 'player-url',
    status: 'NSO',
    pronouns: ['she', 'her'],
  },
];

export default Players;
